### ISSUE TITLE
Fix google maps integration

### ISSUE THREAD

**Issue by dsanch3z** [cube5/contacts-app#2]
When adding new contact, a google maps appear, but has no funcionality yet.

---

**Tasks:**
- [ ] Add search box to map
- [ ] Add marker functionality
- [ ] When selecting address, show in 'Address' field
